[versions]
accompanist = "0.32.0"
android-billing = "6.1.0"
androidx-activity = "1.8.1"
androidx-livedata = "2.6.2"
androidx-profileinstaller = "1.3.1"
androidx-startup = "1.2.0-alpha02"
androidx-work = "2.9.0"
androidx-room = "2.6.1"
androidx-appcompat = "1.7.0-alpha03"
androidx-compose = "1.6.0-beta02"
androidx-wear = "1.3.0-beta01"
androidx-navigation = "2.7.5"
androidx-palette = "1.0.0"
androidx-process = "2.6.2"
androidx-splash = "1.1.0-alpha02"
google-auth = "20.7.0"
google-material = "1.12.0-alpha03"
google-update = "2.1.0"
google-services = "4.4.0"
google-location = "21.0.1"
google-review = "2.0.1"
google-wearable = "18.1.0"
compose-material3 = "1.2.0-alpha12"
compose-compiler = "1.5.4"
firebase-analytics = "21.5.0"
firebase-crashlytics = "18.6.0"
firebase-plugin = "2.9.9"
hilt-compiler = "1.1.0"
hilt-navigation = "1.1.0"
hilt-work = "1.1.0"
kotlin = "1.9.21"
collections = "0.3.7"
android = "8.2.0"
coil = "2.5.0"
hilt = "2.50"
json = "1.6.2"
coroutines = "1.7.3"
ktor = "2.3.7"
mockito-kotlin = "5.2.1"
mockito-core = "5.9.0"
zxing = "3.5.2"
zxing-embed = "4.3.0"
ksp = "1.9.21-1.0.15"
junit = "1.1.5"
espresso-core = "3.5.1"
uiautomator = "2.2.0"
benchmark-macro-junit4 = "1.2.2"
instant = "18.0.1"
haze = "0.4.5"

[libraries]
android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "android-billing" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "androidx-livedata" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-process" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
google-update = { module = "com.google.android.play:app-update-ktx", version.ref = "google-update" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
google-location = { module = "com.google.android.gms:play-services-location", version.ref = "google-location" }
google-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-auth" }
google-review = { module = "com.google.android.play:review-ktx", version.ref = "google-review" }
google-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "google-wearable" }
google-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
google-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
google-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
google-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
google-instant = { module = "com.google.android.gms:play-services-instantapps", version.ref = "instant" }
google-haze = { module = "dev.chrisbanes.haze:haze-jetpack-compose", version.ref = "haze" }
compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
compose-ui-window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }
compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear" }
compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear" }
compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-plugin" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
hilt-compiler2 = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
zxing-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing-embed" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
konfetti = { module = "nl.dionsegijn:konfetti-compose", version = "2.0.4" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android" }
android-application = { id = "com.android.application", version.ref = "android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidTest = { id = "com.android.test", version.ref = "android" }

[bundles]
compose = [
    "compose-ui-core",
    "compose-activity",
    "compose-material",
    "compose-material3",
    "compose-foundation",
    "compose-navigation",
    "compose-ui-test",
    "compose-ui-tooling",
    "compose-ui-window",
    "kotlinx-collections"
]
compose-wear = [
    "compose-wear-navigation",
    "compose-wear-foundation",
    "compose-wear-material",
]